package com.github.unqui

private fun addUsers(noteService: NoteService) {
    noteService.register(UserDraft("tomas@gmail.com", "https://robohash.org/eumutvoluptatem.jpg?size=50x50&set=set1", "tomas", "tomas"))
    noteService.register(UserDraft("juan@gmail.com", "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1", "juan", "juan"))
    noteService.register(UserDraft("anita@gmail.com", "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1", "anita", "anita"))
    noteService.register(UserDraft("a@gmail.com", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "a", "a"))
    noteService.register(UserDraft("b@gmail.com", "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1", "b", "b"))
    noteService.register(UserDraft("c@gmail.com", "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1", "c", "c"))
}

private fun addNotes(noteService: NoteService) {
    noteService.addNote("user_1", NoteDraft("danger disorder", "He always wore his sunglasses at night. It was the first time he had ever seen someone cook dinner on an elephant."))
    noteService.addNote("user_1", NoteDraft("teacher vision", "She was only made the society president because she can whistle with her toes. She couldn't decide of the glass was half empty or half full so she drank it."))
    noteService.addNote("user_1", NoteDraft("resolution bomber", "The wake behind the boat told of the past while the open sea for told life in the unknown future. I've traveled all around Africa and still haven't found the gnu who stole my scarf."))
    noteService.addNote("user_1", NoteDraft("senior meet", "Although it wasn't a pot of gold, Nancy was still enthralled at what she found at the end of the rainbow. She traveled because it cost the same as therapy and was a lot more enjoyable."))
    noteService.addNote("user_1", NoteDraft("belt charismatic", "The rain pelted the windshield as the darkness engulfed us. Charles ate the french fries knowing they would be his last meal."))
    noteService.addNote("user_1", NoteDraft("blonde bang", "The secret ingredient to his wonderful life was crime. The shooter says goodbye to his love."))
    noteService.addNote("user_1", NoteDraft("audience training", "Courage and stupidity were all he had. The beauty of the African sunset disguised the danger lurking nearby."))
    noteService.addNote("user_1", NoteDraft("service recovery", "Written warnings in instruction manuals are worthless since rabbits can't read. She saw the brake lights, but not in time."))
    noteService.addNote("user_1", NoteDraft("neutral rainbow", "The white water rafting trip was suddenly halted by the unexpected brick wall. He wondered if she would appreciate his toenail collection."))
    noteService.addNote("user_1", NoteDraft("seem sword", "We have never been to Asia, nor have we visited Africa. When money was tight, he'd get his lunch money from the local wishing well."))
    noteService.addNote("user_1", NoteDraft("output temporary", "He invested some skill points in Charisma and Strength. It isn't difficult to do a handstand if you just stand on your hands."))
    noteService.addNote("user_2", NoteDraft("sister chapter", "Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind. It was difficult for Mary to admit that most of her workout consisted of exercising poor judgment."))
    noteService.addNote("user_2", NoteDraft("pile gear", "I may struggle with geography, but I'm sure I'm somewhere around here. It was the scarcity that fueled his creativity."))
    noteService.addNote("user_2", NoteDraft("widen drawing", "The most exciting eureka moment I've had was when I realized that the instructions on food packets were just guidelines."))
    noteService.addNote("user_2", NoteDraft("declaration obscure", "People keep telling me \"orange\" but I still prefer \"pink\". He never understood why what, when, and where left out who."))
    noteService.addNote("user_2", NoteDraft("package age", "He was surprised that his immense laziness was inspirational to others. Everyone was curious about the large white blimp that appeared overnight."))
    noteService.addNote("user_2", NoteDraft("host period", "I met an interesting turtle while the song on the radio blasted away. One small action would change her life, but whether it would be for better or for worse was yet to be determined."))
    noteService.addNote("user_2", NoteDraft("huge insurance", "All she wanted was the answer, but she had no idea how much she would hate it. It dawned on her that others could make her happier, but only she could make herself happy."))
    noteService.addNote("user_2", NoteDraft("sulphur circle", "When he had to picnic on the beach, he purposely put sand in other people’s food. I love bacon, beer, birds, and baboons."))
    noteService.addNote("user_2", NoteDraft("clerk scene", "I’m working on a sweet potato farm. He wondered if it could be called a beach if there was no sand."))
    noteService.addNote("user_2", NoteDraft("body penalty", "Nancy decided to make the porta-potty her home. Love is not like pizza. She had the gift of being able to paint songs."))
    noteService.addNote("user_2", NoteDraft("bed loyalty", "The urgent care center was flooded with patients after the news of a new deadly virus was made public. I want a giraffe, but I'm a turtle eating waffles."))
    noteService.addNote("user_2", NoteDraft("drill reproduce", "Nobody loves a pig wearing lipstick. Mom didn’t understand why no one else wanted a hot tub full of jello."))
    noteService.addNote("user_2", NoteDraft("jurisdiction reckless", "With a single flip of the coin, his life changed forever. The elephant didn't want to talk about the person in the room."))
    noteService.addNote("user_2", NoteDraft("beef straight", "Too many prisons have become early coffins. She did not cheat on the test, for it was not the right thing to do."))
    noteService.addNote("user_3", NoteDraft("underline defendant", "His ultimate dream fantasy consisted of being content and sleeping eight hours in a row. Bill ran from the giraffe toward the dolphin."))
    noteService.addNote("user_3", NoteDraft("agency age", "Homesickness became contagious in the young campers' cabin. The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle’s disappearance."))
    noteService.addNote("user_3", NoteDraft("lake counter", "We're careful about orange ping pong balls because people might think they're fruit. The doll spun around in circles in hopes of coming alive."))
    noteService.addNote("user_3", NoteDraft("practical lobby", "There were three sphered rocks congregating in a cubed room. She had convinced her kids that any mushroom found on the ground would kill them if they touched it."))
    noteService.addNote("user_3", NoteDraft("long panel", "I always dreamed about being stranded on a desert island until it actually happened. There should have been a time and a place, but this wasn't it."))
    noteService.addNote("user_3", NoteDraft("bald vain", "Everybody should read Chaucer to improve their everyday vocabulary. If eating three-egg omelets causes weight-gain, budgie eggs are a good substitute."))
    noteService.addNote("user_3", NoteDraft("comfortable", "She was too short to see over the fence. He had decided to accept his fate of accepting his fate."))
    noteService.addNote("user_3", NoteDraft("oak brink", "Tomatoes make great weapons when water balloons aren’t available. It must be five o'clock somewhere."))
    noteService.addNote("user_3", NoteDraft("common side", "Today is the day I'll finally know what brick tastes like. The father handed each child a roadmap at the beginning of the 2-day road trip and explained it was so they could find their way home."))
    noteService.addNote("user_3", NoteDraft("opposed", "They got there early, and they got really good seats. Douglas figured the best way to succeed was to do the opposite of what he'd been doing all his life."))
    noteService.addNote("user_3", NoteDraft("assessment", "She was the type of girl who wanted to live in a pink house. Henry couldn't decide if he was an auto mechanic or a priest."))
    noteService.addNote("user_3", NoteDraft("means monster", "Love is not like pizza. It isn't difficult to do a handstand if you just stand on your hands."))
    noteService.addNote("user_3", NoteDraft("healthy pedestrian", "They say that dogs are man's best friend, but this cat was setting out to sabotage that theory. Combines are no longer just for farms."))
    noteService.addNote("user_4", NoteDraft("couple method", "You're good at English when you know the difference between a man eating chicken and a man-eating chicken. I met an interesting turtle while the song on the radio blasted away."))
    noteService.addNote("user_4", NoteDraft("classroom catch", "If I don’t like something, I’ll stay away from it. With the high wind warning There are few things better in life than a slice of pie."))
    noteService.addNote("user_4", NoteDraft("float party", "He set out for a short walk, but now all he could see were mangroves and water were for miles. She wanted a pet platypus but ended up getting a duck and a ferret instead."))
    noteService.addNote("user_4", NoteDraft("remark modernize", "I am my aunt's sister's daughter. The hand sanitizer was actually clear glue."))
    noteService.addNote("user_4", NoteDraft("achieve patrol", "Today I heard something new and unmemorable. As he entered the church he could hear the soft voice of someone whispering into a cell phone."))
    noteService.addNote("user_4", NoteDraft("autonomy major", "The bug was having an excellent day until he hit the windshield. I come from a tribe of head-hunters, so I will never need a shrink."))
    noteService.addNote("user_4", NoteDraft("crutch large", "I'd always thought lightning was something only I could see. He watched the dancing piglets with panda bear tummies in the swimming pool."))
    noteService.addNote("user_4", NoteDraft("veteran trail", "They were excited to see their first sloth. Her daily goal was to improve on yesterday."))
    noteService.addNote("user_4", NoteDraft("bulletin", "The teenage boy was accused of breaking his arm simply to get out of the test."))
    noteService.addNote("user_4", NoteDraft("relate yearn", "I love bacon, beer, birds, and baboons. He was the type of guy who liked Christmas lights on his house in the middle of July."))
    noteService.addNote("user_4", NoteDraft("variable", "He's in a boy band which doesn't make much sense for a snake. I was starting to worry that my pet turtle could tell what I was thinking."))
    noteService.addNote("user_4", NoteDraft("cultural", "One small action would change her life, but whether it would be for better or for worse was yet to be determined. The light that burns twice as bright burns half as long."))
    noteService.addNote("user_4", NoteDraft("convenience", "I purchased a baby clown from the Russian terrorist black market. I think I will buy the red car, or I will lease the blue one."))
    noteService.addNote("user_4", NoteDraft("mix fisherman", "You bite up because of your lower jaw. He dreamed of eating green apples with worms."))
    noteService.addNote("user_5", NoteDraft("temptation ego", "Douglas figured the best way to succeed was to do the opposite of what he'd been doing all his life."))
    noteService.addNote("user_5", NoteDraft("policeman miscarriage", "It would have been a better night if the guys next to us weren't in the splash zone."))
    noteService.addNote("user_5", NoteDraft("act mountain", "The teens wondered what was kept in the red shed on the far edge of the school grounds."))
    noteService.addNote("user_5", NoteDraft("favourite request", "If any cop asks you where you were, just say you were visiting Kansas. I am happy to take your donation; any amount will be greatly appreciated."))
    noteService.addNote("user_5", NoteDraft("energy bay", "I covered my friend in baby oil. There were white out conditions in the town; subsequently, the roads were impassable."))
    noteService.addNote("user_5", NoteDraft("unity stake", "She had a difficult time owning up to her own crazy self. She opened up her third bottle of wine of the night."))
    noteService.addNote("user_5", NoteDraft("roll sulphur", "My biggest joy is roasting almonds while stalking prey. Written warnings in instruction manuals are worthless since rabbits can't read."))
    noteService.addNote("user_5", NoteDraft("enjoy minister", "As the rental car rolled to a stop on the dark road, her fear increased by the moment. The sudden rainstorm washed crocodiles into the ocean."))
    noteService.addNote("user_5", NoteDraft("constellation", "Today I bought a raincoat and wore it on a sunny day. Hit me with your pet shark!"))
    noteService.addNote("user_5", NoteDraft("loop deputy", "Tom got a small piece of pie. He drank life before spitting it out. The stench from the feedlot permeated the car despite having the air conditioning on recycled air."))
    noteService.addNote("user_5", NoteDraft("shrink presidential", "He ran out of money, so he had to stop playing poker. Little Red Riding Hood decided to wear orange today."))
    noteService.addNote("user_5", NoteDraft("speed boom", "He colored deep space a soft yellow. He knew it was going to be a bad day when he saw mountain lions roaming the streets."))
    noteService.addNote("user_5", NoteDraft("kettle generate", "The memory we used to share is no longer coherent. The river stole the gods."))
    noteService.addNote("user_5", NoteDraft("progressive strong", "My Mum tries to be cool by saying that she likes all the same things that I do."))
    noteService.addNote("user_0", NoteDraft("inspiration", "She had that tint of craziness in her soul that made her believe she could actually make a difference."))
    noteService.addNote("user_0", NoteDraft("talkative tired", "The stranger officiates the meal. The old apple revels in its authority."))
    noteService.addNote("user_0", NoteDraft("cafe folklore", "At that moment she realized she had a sixth sense. It must be easy to commit crimes as a snake because you don't have to worry about leaving fingerprints."))
    noteService.addNote("user_0", NoteDraft("strap copy", "As he looked out the window, he saw a clown walk by. It doesn't sound like that will ever be on my travel list."))
    noteService.addNote("user_0", NoteDraft("location thesis", "The bullet pierced the window shattering it before missing Danny's head by mere millimeters. It was a really good Monday for being a Saturday."))
    noteService.addNote("user_0", NoteDraft("gift money", "He waited for the stop sign to turn to a go sign. Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over."))

}

fun getNoteService(): NoteService {
    val noteService = NoteService()
    addUsers(noteService)
    addNotes(noteService)
    return noteService
}
